# docker-compose.yml
version: "3.1"
services:
  web:
    build:
      context: ./web-server
      dockerfile: Dockerfile
    container_name: web-server
    command: poetry run daphne -b0.0.0.0 -p8000 backend.asgi:application
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    build:
        context: ./db
        dockerfile: Dockerfile
    container_name: MariaDB
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: root
      MYSQL_PASSWORD: user1234
      MYSQL_ROOT_PASSWORD: user1234
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/data/conf.d:/etc/mysql/conf.d
  redis:
    image: redis:latest
    container_name: Redis
    ports:
      - "6379:6379"
