# docker-compose.yml
version: "1"
services:
  web:
    build:
      context: ./web-server
      dockerfile: Dockerfile
    container_name: web-server
    command: pooetry run daphne -b 0.0.0.0 -p 8000 backend.asgi:application
    expose:
      - "8000"
    depends_on:
      - db
  db:
    image: mariadb:latest
    container_name: mysql
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: user1234
      MYSQL_ROOT_PASSWORD: user1234
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/data/conf.d:/etc/mysql/conf.d
